new_names = {
    'POS - Android\\Delivery': 'POS - Android',
    'POS - Android\\android-core\\Bug Solvers Team': 'POS - Android',
    'POS - Android\\android-core\\Telemetry team': 'POS - Android',
    'POS - Android\\android-core': 'POS - Android',
    'POS - Mobile SDK\\Development': 'POS - Mobile SDK',
    'POS - Mobile SDK\\Development\\android-sdk': 'POS - Mobile SDK',
    'chapter-sre\\Gestão': 'Gestão',
    'chapter-sre\\Engenharia - Operação': 'chapter-sre\\Engenharia - Operação',
    'chapter-sre\\Engenharia - Operação\\Automação Service Account GCP': 'Automação Service Account GCP',
    'chapter-sre\\Engenharia - Operação\\Automação Firewall GCP': 'Automação Firewall GCP',
    'chapter-sre\\Atlas': 'Atlas',
    'chapter-sre\\Engenharia - Operação\\Automação Org GCP Stone': 'Automação Org GCP Stone',
    'chapter-sre\\Asset': 'Asset',
    'frt-celebro': 'Célebro',
    'Fin-Payments': 'Fin-Payments',
    'fin-acquirer\\Acquiring Kanban': 'fin-acquirer\\Acquiring Kanban',
    'pro-financial-transparency': 'pro-financial-transparency',
    'trs-funding': 'trs-funding',
    'trs-risk': 'trs-risk' ,
    'trs-stock': 'trs-stock',
    'frt-growth\\Loja': 'Site Stone',
    'frt-growth': 'Site Stone',
    'frt-growth\\Site': 'Site Stone',
    'fin-creditlock': 'Creditlock',
    'frt-portal\\Adquirencia': 'Portal Cliente Stone',
    'frt-portal\\Multiprodutos': 'Portal Cliente Stone',
    'frt-portal': 'Portal Cliente Stone',
    'frt-portal\\Produtos Financeiros': 'Portal Cliente Stone',

    # Select Financial
    'Sistema de Pagamentos': 'Sistema de Pagamentos',
    'Sistema de Saldo': 'Sistema de Saldo',
    'Sistema de Liquidação': 'Sistema de Liquidação',
    'Acquirer API': 'Acquirer API',
    'Motor de Retenção': 'Motor de Retenção',
    'API de antecipação': 'API de antecipação',
    'Financial Statement': 'Financial Statement',
    'Conciliação': 'Conciliação',
    'Cessão à Receber': 'Cessão à Receber',
    'API de Notificação': 'API de Notificação',
    'Portal de Operações Tesouraria': 'Portal de Operações Tesouraria',
    'API Gateway Tesouraria': 'API Gateway Tesouraria',
    'Cessão à Pagar':'Cessão à Pagar',
    'Risk': 'Risk',
    'Asset Trader':'Asset Trader',
    'AutoAssign': 'AutoAssign',
    'Gestor de Ativos' :  'Gestor de Ativos',
    'Curva DI': 'Curva DI',

}
